[font]
size = 16

[font.bold_italic]
family = "mononoki Nerd Font Mono"

[font.bold]
family = "mononoki Nerd Font Mono"

[font.italic]
family = "mononoki Nerd Font Mono"

[font.normal]
family = "mononoki Nerd Font Mono"
